development: localhost:6379
staging: redis://redistogo:04d94fde444a24fc1e85d91e1be9f59d@barreleye.redistogo.com:11575/
production: redis://redistogo:8b95925b5c9cac0ac7e25aca555c9daa@pearlfish.redistogo.com:10272/