require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LiteraturesController do
#
#  # This should return the minimal set of attributes required to create a valid
#  # Literature. As you add validations to Literature, be sure to
#  # adjust the attributes here as well.
#  let(:valid_attributes) { { "name" => "MyString" } }
#
#  # This should return the minimal set of values that should be in the session
#  # in order to pass any filters (e.g. authentication) defined in
#  # LiteraturesController. Be sure to keep this updated too.
#  let(:valid_session) { {} }
#
#  describe "GET index" do
#    it "assigns all literatures as @literatures" do
#      literature = Literature.create! valid_attributes
#      get :index, {}, valid_session
#      assigns(:literatures).should eq([literature])
#    end
#  end
#
#  describe "GET show" do
#    it "assigns the requested literature as @literature" do
#      literature = Literature.create! valid_attributes
#      get :show, {:id => literature.to_param}, valid_session
#      assigns(:literature).should eq(literature)
#    end
#  end
#
#  describe "GET new" do
#    it "assigns a new literature as @literature" do
#      get :new, {}, valid_session
#      assigns(:literature).should be_a_new(Literature)
#    end
#  end
#
#  describe "GET edit" do
#    it "assigns the requested literature as @literature" do
#      literature = Literature.create! valid_attributes
#      get :edit, {:id => literature.to_param}, valid_session
#      assigns(:literature).should eq(literature)
#    end
#  end
#
#  describe "POST create" do
#    describe "with valid params" do
#      it "creates a new Literature" do
#        expect {
#          post :create, {:literature => valid_attributes}, valid_session
#        }.to change(Literature, :count).by(1)
#      end
#
#      it "assigns a newly created literature as @literature" do
#        post :create, {:literature => valid_attributes}, valid_session
#        assigns(:literature).should be_a(Literature)
#        assigns(:literature).should be_persisted
#      end
#
#      it "redirects to the created literature" do
#        post :create, {:literature => valid_attributes}, valid_session
#        response.should redirect_to(Literature.last)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns a newly created but unsaved literature as @literature" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Literature.any_instance.stub(:save).and_return(false)
#        post :create, {:literature => { "name" => "invalid value" }}, valid_session
#        assigns(:literature).should be_a_new(Literature)
#      end
#
#      it "re-renders the 'new' template" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Literature.any_instance.stub(:save).and_return(false)
#        post :create, {:literature => { "name" => "invalid value" }}, valid_session
#        response.should render_template("new")
#      end
#    end
#  end
#
#  describe "PUT update" do
#    describe "with valid params" do
#      it "updates the requested literature" do
#        literature = Literature.create! valid_attributes
#        # Assuming there are no other literatures in the database, this
#        # specifies that the Literature created on the previous line
#        # receives the :update_attributes message with whatever params are
#        # submitted in the request.
#        Literature.any_instance.should_receive(:update).with({ "name" => "MyString" })
#        put :update, {:id => literature.to_param, :literature => { "name" => "MyString" }}, valid_session
#      end
#
#      it "assigns the requested literature as @literature" do
#        literature = Literature.create! valid_attributes
#        put :update, {:id => literature.to_param, :literature => valid_attributes}, valid_session
#        assigns(:literature).should eq(literature)
#      end
#
#      it "redirects to the literature" do
#        literature = Literature.create! valid_attributes
#        put :update, {:id => literature.to_param, :literature => valid_attributes}, valid_session
#        response.should redirect_to(literature)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns the literature as @literature" do
#        literature = Literature.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Literature.any_instance.stub(:save).and_return(false)
#        put :update, {:id => literature.to_param, :literature => { "name" => "invalid value" }}, valid_session
#        assigns(:literature).should eq(literature)
#      end
#
#      it "re-renders the 'edit' template" do
#        literature = Literature.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Literature.any_instance.stub(:save).and_return(false)
#        put :update, {:id => literature.to_param, :literature => { "name" => "invalid value" }}, valid_session
#        response.should render_template("edit")
#      end
#    end
#  end
#
#  describe "DELETE destroy" do
#    it "destroys the requested literature" do
#      literature = Literature.create! valid_attributes
#      expect {
#        delete :destroy, {:id => literature.to_param}, valid_session
#      }.to change(Literature, :count).by(-1)
#    end
#
#    it "redirects to the literatures list" do
#      literature = Literature.create! valid_attributes
#      delete :destroy, {:id => literature.to_param}, valid_session
#      response.should redirect_to(literatures_url)
#    end
#  end

end
